### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by Alice-302** [Surrey-UP-Lab/RegionSpot#12]
Excuse me about how long the training cycle is?

**Comment by happy-hsy** [comment]
We implement a two-stage training process. In Stage 1, we train using Objects365, and in Stage 2, we use a combination of Objects365, OpenImages, and V3Det. Each stage requires approximately 12-15 hours to complete 450,000 iterations.

**Comment by happy-hsy** [comment]
Thank you for your interest. I recommend downloading all the data for training to achieve the best performance. However, if storage is a constraint, you can use a portion of the OpenImages dataset for training, though this may result in decreased performance. We have not tested this approach. Regarding training time, we have not conducted training using only two parts of the dataset, and it may require many iterations.
